### PR TITLE
fix: highlight html attachments and some improvements

### LINKED ISSUE #487: Fix attachment preview mode
Currently, when an HTML attachment is expanded in the test body tree, its markup is shown:

Image

There is no way to preview the attachment here. To view the rendered HTML, users must first open the attachment in the fullscreen mode:

Image

There are three problems here:

1. There is a toggle that switches between the preview and the toggle, but it doesn't work.
2. The height of the rendered document is limited. It should be easily fixable by applying `height: 100%` to the parent of the `iframe`.
3. There are no styles affecting the rendered area. The background is white and the default fonts are used. This is especially noticeable in the dark theme:
   Image

### Proposal

1. Fix the preview/code toggle.
2. Fix the height of the render area.
3. Fix the styles of the rendered area if possible.
4. Add the preview/code toggle to the attachment row in the test body tree.   Motivation: It's not obvious to users that there are additional capabilities available when the attachment is in the fullscreen mode. The button just says "Expand." Hence, most assume there is no way to view the rendered attachment.
This should affect all previewable attachments:

  - `text/html`
  - `text/csv`
  - `text/markdown`
  - `text/tab-separated-values`
  - `text/uri-list`

### PR DESCRIPTION
**Pull request by todti**
- Fix #487 

image
image
HTML attachments are rendered in a sandboxed iframe with theme injection; layout fixes for the preview container so the iframe fills the available space correctly.

### Attachments:
 - **Syntax highlighting** in attachment code blocks: language detection from `contentType`/file extension, token rendering.
- **Syntax highlighting** toggle in the modal and in the attachment row
- **Preview** / **View code** buttons.
- Fix collapsed/expanded for steps with attachments

image

### Section state
- Collapsed/expanded state persisted in `localStorage` for: test body, steps, attachments, Labels, Parameters, Description, Links.
- Limit of 8 items with **Show more** / **Show less** for Labels, Parameters, Links, Variables, Metadata sections. Section is collapsed by default when there are more than 8 items; expanded state is persisted.

### CODE REVIEW

File: packages/web-components/src/components/Modal/index.tsx [hunk 1]
```diff
@@ -36,32 +36,97 @@ export interface ModalTranslationsProps {
...
+  "text/html",
+  "text/xml",
+  "application/xml",
+  "text/css",
+  "text/csv",
+  "text/tab-separated-values",
+  "text/markdown",
+]);
+
+const syntaxHighlightExtensions = new Set([
```
Comment (epszaw) [inline packages/web-components/src/components/Modal/index.tsx]: Use code from **[web-commons](https://github.com/allure-framework/allure3/pull/513/changes#diff-f5aab43583ead5186ba43465124e607ccf31e65c8591f232886c49bbfd1a01a7R123-R172)** package

File: packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx [hunk 2]
```diff
@@ -51,17 +52,74 @@ const iconMap: Record<string, string> = {
   "application/vnd.allure.playwright-trace": playwrightLogo,
 };
 
+const HAS_PREVIEW_COMPONENT: Record<string, boolean> = {
+  html: true,
+};
+
+const syntaxHighlightContentTypes = new Set([
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx]: Same here, re-use code from `web-commons` package

File: packages/web-awesome/src/components/TestResult/TrOverview.tsx [hunk 3]
```diff
@@ -11,14 +11,26 @@ import { TrPwTraces } from "@/components/TestResult/TrPwTraces";
...
+    groupedLabels,
+    links,
+    descriptionHtml,
+    setup,
+    steps,
+    teardown,
+    id: testResultId,
+    status,
+  } = testResult || {};
+  const id = testResultId ?? currentTrId.value;
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrOverview.tsx]: It's not obvious, what does `id` mean. Let's rename it to something else.
Maybe, reverse to `testResultId -> id` and use `testResultId` for the constant will be better.

File: packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx [hunk 4]
```diff
@@ -51,17 +52,74 @@ const iconMap: Record<string, string> = {
...
   const { t: tAttachments } = useI18n("attachments");
   const { link } = item;
   const { missed } = link;
   const componentType = attachmentType(link.contentType);
   const isValidComponentType = !["archive", null].includes(componentType);
+  const isPreviewable = isPreviewableContentType(link.contentType) && HAS_PREVIEW_COMPONENT[componentType ?? ""];
+  const isCodeView = (componentType === "code" || componentType === "text") && (!isPreviewable || !showPreview);
+  const contentType = link.contentType?.toLowerCase();
+  const ext = link.ext?.replace(".", "").toLowerCase();
+  const isSyntaxHighlightable =
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx]: All these utilities also can be stored in `web-commons` package and then re-used across your code

File: packages/web-commons/src/attachments.ts [hunk 5]
```diff
@@ -120,6 +120,104 @@ export type AttachmentType =
...
+  "cs",
+  "scala",
+  "dart",
+  "lua",
+  "haskell",
+  "r",
+  "perl",
+]);
+
+const pickExtension = (...parts: (string | undefined)[]) => {
```
Comment (epszaw) [inline packages/web-commons/src/attachments.ts]: Why can't we use `extname` from `node:path` package?

File: packages/web-commons/src/attachments.ts [hunk 6]
```diff
@@ -120,6 +120,104 @@ export type AttachmentType =
...
+  originalFileName?: string;
+}): boolean => {
+  if (!payload) {
+    return false;
+  }
+
+  const contentType = payload.contentType?.toLowerCase();
+  const ext = pickExtension(payload.ext, payload.name, payload.originalFileName);
+
+  if (contentType === "text/plain" || contentType === "text/*" || contentType === "text/uri-list") {
```
Comment (epszaw) [inline packages/web-commons/src/attachments.ts]: I think it's enough just to have a list of supported extensions and content types and then check, is given argument present in the list or not. Current logic looks a bit overcomplicated

File: packages/web-awesome/src/components/TestResult/TrMetadata/index.tsx [hunk 7]
```diff
@@ -1,26 +1,65 @@
...
 import type { FunctionalComponent } from "preact";
-import { useState } from "preact/hooks";
 import type { AwesomeTestResult } from "types";
 import { TrMetadataList } from "@/components/Metadata";
 import { MetadataButton } from "@/components/MetadataButton";
 import { useI18n } from "@/stores/locale";
+import { collapsedTrees, toggleTree } from "@/stores/tree";
 import * as styles from "./styles.scss";
 
+const LABELS_VISIBLE_LIMIT = 8;
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrMetadata/index.tsx]:
```suggestion
const VISIBLE_LABELS_LIMIT = 8;
```

File: packages/web-awesome/src/components/TestResult/TrLinks/index.tsx [hunk 8]
```diff
@@ -1,11 +1,13 @@
...
+import { Button, SvgIcon, Text, allureIcons } from "@allurereport/web-components";
 import type { FunctionalComponent } from "preact";
-import { useState } from "preact/hooks";
 import type { AwesomeTestResult } from "types";
 import { MetadataButton } from "@/components/MetadataButton";
 import { useI18n } from "@/stores/locale";
+import { collapsedTrees, toggleTree } from "@/stores/tree";
 import * as styles from "./styles.scss";
 
+const LINKS_VISIBLE_LIMIT = 8;
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrLinks/index.tsx]:
```suggestion
const VISIBLE_LINKS_LIMIT = 8;
```

**Review by epszaw — CHANGES_REQUESTED** [review]
Mostly, there are many lines of duplicated code. Let's re-use the logic by moving the code to common packages.

The logic works as expected.

File: packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx [hunk 9]
```diff
@@ -51,17 +52,32 @@ const iconMap: Record<string, string> = {
   "application/vnd.allure.playwright-trace": playwrightLogo,
 };
 
+const HAS_PREVIEW_COMPONENT: Record<string, boolean> = {
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx]: Could be `Set` which is simpler

File: packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx [hunk 10]
```diff
@@ -51,17 +52,32 @@ const iconMap: Record<string, string> = {
...
+  html: true,
+};
+
 export const TrAttachment: FunctionComponent<{
   item: AttachmentTestStepResult;
   stepIndex?: number;
   className?: string;
 }> = ({ item, stepIndex }) => {
-  const [isOpened, setIsOpen] = useState(false);
+  const attachmentTreeId = item.link?.id != null ? `attachment-${item.link.id}` : null;
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx]: `!=` -> `!==`

File: packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx [hunk 11]
```diff
@@ -51,17 +52,32 @@ const iconMap: Record<string, string> = {
...
+  const isOpened = attachmentTreeId == null || !collapsedTrees.value.has(attachmentTreeId);
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx]: It's enough to leave just `!collapsedTrees.value.has(attachmentTreeId)`

File: packages/web-awesome/src/components/TestResult/TrDescription/index.tsx [hunk 12]
```diff
@@ -3,16 +3,19 @@ import type { FunctionalComponent } from "preact";
...
   descriptionHtml: AwesomeTestResult["descriptionHtml"];
 };
 
 const MIN_HEIGHT = 120;
 
-export const TrDescription: FunctionalComponent<TrDescriptionProps> = ({ descriptionHtml }) => {
-  const [isOpen, setIsOpen] = useState(true);
+export const TrDescription: FunctionalComponent<TrDescriptionProps> = ({ id, descriptionHtml }) => {
+  const descriptionId = id !== null ? `${id}-description` : null;
+  const isOpen = descriptionId == null || !collapsedTrees.value.has(descriptionId);
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrDescription/index.tsx]: Just `!collapsedTrees.value.has(descriptionId)`

File: packages/web-awesome/src/components/TestResult/TrLinks/index.tsx [hunk 13]
```diff
@@ -35,21 +37,53 @@ const TrLink: FunctionalComponent<{
...
 };
 
-export const TrLinks: FunctionalComponent<TrLinksProps> = ({ links }) => {
-  const [isOpened, setIsOpen] = useState(true);
+export const TrLinks: FunctionalComponent<TrLinksProps> = ({ id, links }) => {
   const { t } = useI18n("ui");
-  const linkMap = links.map((link, index) => {
+  const linksId = id !== null ? `${id}-links` : null;
+  const linksShowAllId = id !== null ? `${id}-links-showAll` : null;
+  const isOpened = linksId == null || !collapsedTrees.value.has(linksId);
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrLinks/index.tsx]: Just `!collapsedTrees.value.has(linksId)`

File: packages/web-awesome/src/components/TestResult/TrLinks/index.tsx [hunk 14]
```diff
@@ -35,21 +37,53 @@ const TrLink: FunctionalComponent<{
...
+  const showAll = linksShowAllId !== null && collapsedTrees.value.has(linksShowAllId);
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrLinks/index.tsx]: Just `collapsedTrees.value.has(linksShowAllId)`

File: packages/web-awesome/src/components/TestResult/TrLinks/index.tsx [hunk 15]
```diff
@@ -35,21 +37,53 @@ const TrLink: FunctionalComponent<{
...
+  const totalCount = links.length;
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrLinks/index.tsx]: Why can't we use just `links.length`?

File: packages/web-awesome/src/components/TestResult/TrMetadata/index.tsx [hunk 16]
```diff
@@ -1,26 +1,65 @@
...
+export const TrMetadata: FunctionalComponent<TrMetadataProps> = ({ id, testResult }) => {
   const { t } = useI18n("ui");
   const { labels, groupedLabels } = testResult ?? {};
-  const [isOpened, setIsOpened] = useState(true);
+  const labelsId = id !== null ? `${id}-labels` : null;
+  const labelsShowAllId = id !== null ? `${id}-labels-showAll` : null;
+  const isOpened = labelsId == null || !collapsedTrees.value.has(labelsId);
+  const entries = groupedLabels ? Object.entries(groupedLabels) : [];
+  const totalCount = entries.length;
+  const showAll = labelsShowAllId !== null && collapsedTrees.value.has(labelsShowAllId);
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrMetadata/index.tsx]: Just `collapsedTrees.value.has(labelsShowAllId)`

File: packages/web-awesome/src/components/TestResult/TrMetadata/index.tsx [hunk 17]
```diff
@@ -1,26 +1,65 @@
...
 };
 
-export const TrMetadata: FunctionalComponent<TrMetadataProps> = ({ testResult }) => {
+export const TrMetadata: FunctionalComponent<TrMetadataProps> = ({ id, testResult }) => {
   const { t } = useI18n("ui");
   const { labels, groupedLabels } = testResult ?? {};
-  const [isOpened, setIsOpened] = useState(true);
+  const labelsId = id !== null ? `${id}-labels` : null;
+  const labelsShowAllId = id !== null ? `${id}-labels-showAll` : null;
+  const isOpened = labelsId == null || !collapsedTrees.value.has(labelsId);
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrMetadata/index.tsx]: Just `!collapsedTrees.value.has(labelsId)`

File: packages/web-awesome/src/components/TestResult/TrMetadata/index.tsx [hunk 18]
```diff
@@ -1,26 +1,65 @@
...
+  const entries = groupedLabels ? Object.entries(groupedLabels) : [];
+  const totalCount = entries.length;
+  const showAll = labelsShowAllId !== null && collapsedTrees.value.has(labelsShowAllId);
+  const visibleEntries =
+    totalCount <= VISIBLE_LABELS_LIMIT ? entries : showAll ? entries : entries.slice(0, VISIBLE_LABELS_LIMIT);
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrMetadata/index.tsx]: You can leave `showAll ? entries : entries.slice(0, VISIBLE_LABELS_LIMIT)` with pretty the same effect, but the code will be simpler:

Image

File: packages/web-awesome/src/components/TestResult/TrParameters/index.tsx [hunk 19]
```diff
@@ -1,30 +1,63 @@
...
   parameters: AwesomeTestResult["parameters"];
 };
 
-export const TrParameters: FunctionalComponent<TrParametersProps> = ({ parameters }) => {
-  const [isOpened, setIsOpened] = useState(true);
+export const TrParameters: FunctionalComponent<TrParametersProps> = ({ id, parameters }) => {
   const { t } = useI18n("ui");
+  const parametersId = id !== null ? `${id}-parameters` : null;
+  const parametersShowAllId = id !== null ? `${id}-parameters-showAll` : null;
+  const isOpened = parametersId == null || !collapsedTrees.value.has(parametersId);
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrParameters/index.tsx]: Just `!collapsedTrees.value.has(parametersId)`

File: packages/web-awesome/src/components/TestResult/TrParameters/index.tsx [hunk 20]
```diff
@@ -1,30 +1,63 @@
...
+  const list = parameters ?? [];
+  const totalCount = list.length;
+  const showAll = parametersShowAllId !== null && collapsedTrees.value.has(parametersShowAllId);
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrParameters/index.tsx]: Just `collapsedTrees.value.has(parametersShowAllId)`

File: packages/web-awesome/src/components/TestResult/TrParameters/index.tsx [hunk 21]
```diff
@@ -1,30 +1,63 @@
...
+  const visibleList =
+    totalCount <= PARAMETERS_VISIBLE_LIMIT ? list : showAll ? list : list.slice(0, PARAMETERS_VISIBLE_LIMIT);
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrParameters/index.tsx]: Same as [here](https://github.com/allure-framework/allure3/pull/513/changes#r2888534132)

File: packages/web-awesome/src/components/TestResult/TrSteps/index.tsx [hunk 22]
```diff
@@ -25,13 +24,13 @@ type StepComponentProps = FunctionalComponent<{
 }>;
 
 export const TrSteps: FunctionalComponent<TrStepsProps> = ({ steps, id }) => {
-  const stepsId = `${id}-steps`;
-  const isEarlyCollapsed = Boolean(!collapsedTrees.value.has(stepsId));
-  const [isOpened, setIsOpen] = useState<boolean>(isEarlyCollapsed);
+  const stepsId = id !== null ? `${id}-steps` : null;
+  const isOpened = stepsId == null || !collapsedTrees.value.has(stepsId);
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrSteps/index.tsx]: Just `!collapsedTrees.value.has(stepsId)`

File: packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx [hunk 23]
```diff
@@ -51,17 +52,30 @@ const iconMap: Record<string, string> = {
...
+  const attachmentTreeId = item.link?.id !== null ? `attachment-${item.link.id}` : null;
+  const isOpened = !collapsedTrees.value.has(attachmentTreeId);
+  const [showPreview, setShowPreview] = useState(false);
+  const [highlightCode, setHighlightCode] = useState(true);
   const { t: tAttachments } = useI18n("attachments");
   const { link } = item;
   const { missed } = link;
   const componentType = attachmentType(link.contentType);
   const isValidComponentType = !["archive", null].includes(componentType);
+  const isPreviewable = isPreviewableContentType(link.contentType) && HAS_PREVIEW_COMPONENT.has(componentType ?? "");
```
Comment (epszaw) [inline packages/web-awesome/src/components/TestResult/TrSteps/TrAttachment.tsx]: I think, it's impossible case, when we have preview component, but the given content type isn't previewable. Let's keep just `HAS_PREVIEW_COMPONENT.has(componentType ?? "")` it's enough
