### PR TITLE
Fix environment tab & exclude single default env

### LINKED ISSUE #165: Awesome report is broken after Environments is clicked for some test results
**Describe the bug**

The `Environments` tab breaks the Awesome report for some tests.

**To Reproduce**
1. Create a JUnit XML test result file with the following content:
    ```xml
    <?xml version="1.0" encoding="utf-8"?>
    <testsuites>
      <testsuite name="pytest" errors="0" failures="0" skipped="0" tests="1" time="0.015"
        timestamp="2025-05-02T00:38:45.326610">
        <testcase classname="test.welcome_test" name="test_examples_allure_pytest" time="0.000" />
      </testsuite>
    </testsuites>
    ```
2. Generate and open Allure Awesome.
3. Find and open the `test_examples_allure_pytest` test result.
4. Click on the `Environments` tab. Note that the test details section disappears. Additionally, all navigation buttons (tabs, home) stop working.

**Expected behavior**
A list containing one `default` entry is opened. The navigation buttons continue working.

**Screenshots**

Image

**Desktop (please complete the following information):**
 - OS: Mac OS 15.4.1
 - Browser MS Edge
 - Version 135.0.3179.85

**Additional context**

The following error is shown in the console when `Environments` is clicked:

```
app-52d1decd.js:2  Uncaught (in promise) RangeError: Invalid time value
    at KF (app-52d1decd.js:2:589220)
    at R.VB [as constructor] (app-52d1decd.js:2:604970)
    at R.ee [as render] (app-52d1decd.js:2:61967)
    at Z (app-52d1decd.js:2:59135)
    at $ (app-52d1decd.js:2:54606)
    at Z (app-52d1decd.js:2:59353)
    at $ (app-52d1decd.js:2:54606)
    at Z (app-52d1decd.js:2:59353)
    at $ (app-52d1decd.js:2:54606)
    at J (app-52d1decd.js:2:61096)
KF @ app-52d1decd.js:2
VB @ app-52d1decd.js:2
ee @ app-52d1decd.js:2
Z @ app-52d1decd.js:2
$ @ app-52d1decd.js:2
Z @ app-52d1decd.js:2
$ @ app-52d1decd.js:2
Z @ app-52d1decd.js:2
$ @ app-52d1decd.js:2
J @ app-52d1decd.js:2
Z @ app-52d1decd.js:2
$ @ app-52d1decd.js:2
J @ app-52d1decd.js:2
Z @ app-52d1decd.js:2
$ @ app-52d1decd.js:2
Z @ app-52d1decd.js:2
$ @ app-52d1decd.js:2
J @ app-52d1decd.js:2
Z @ app-52d1decd.js:2
$ @ app-52d1decd.js:2
Z @ app-52d1decd.js:2
$ @ app-52d1decd.js:2
Z @ app-52d1decd.js:2
$ @ app-52d1decd.js:2
Z @ app-52d1decd.js:2
$ @ app-52d1decd.js:2
Z @ app-52d1decd.js:2
B @ app-52d1decd.js:2
Promise.then
I @ app-52d1decd.js:2
R.setState @ app-52d1decd.js:2
r.__c.r.__ @ app-52d1decd.js:2
onClick @ app-52d1decd.js:2
(anonymous) @ app-52d1decd.js:2
[NEW] Explain Console errors by using Copilot in Edge: click
         
         to explain an error. 
        Learn more
        Don't show again

```

### PR DESCRIPTION
**Pull request by epszaw**
fixes #165

### CODE REVIEW

**Review by todti — APPROVED** [review]

File: packages/web-awesome/src/components/TestResult/TrEnvironmentsView/index.tsx [hunk 1]
```diff
@@ -39,7 +39,10 @@ export const TrEnvironmentsView: FunctionalComponent<{
       <Loadable<Record<string, TestEnvGroup>, TestEnvGroup | undefined>
         source={testEnvGroupsStore}
         renderData={(group) => {
-          if (!group) {
+          const envsCount = Object.keys(group?.testResultsByEnv ?? {}).length ?? 0;
+          const emptyEnvs = envsCount === 1 && DEFAULT_ENVIRONMENT in group.testResultsByEnv;
```
Comment (delatrie) [inline packages/web-awesome/src/components/TestResult/TrEnvironmentsView/index.tsx]: The previous line makes it possible to get `envsCount === 0`. In that case, maybe it would be more reasonable to go through the empty envs branch too for consistency? 

For example, we may put some short info on how to set up envs with the link to the docs if no envs are detected. And that info will make sense for both cases.

File: packages/web-awesome/src/components/TestResult/TrInfo/index.tsx [hunk 2]
```diff
@@ -71,14 +71,20 @@ export const TrInfo: FunctionalComponent<TrInfoProps> = ({ testResult }) => {
...
-                <TrTab id="environments" disabled={!group}>
-                  <div className={styles["test-result-tab"]}>
-                    {t("environments")}
-                    {Boolean(group) && <Counter size={"s"} count={Object.keys(group.testResultsByEnv).length} />}
-                  </div>
-                </TrTab>
-              )}
+              renderData={(group) => {
+                const envsCount = Object.keys(group?.testResultsByEnv ?? {}).length ?? 0;
+                const emptyEnvs = envsCount === 1 && DEFAULT_ENVIRONMENT in group.testResultsByEnv;
```
Comment (delatrie) [inline packages/web-awesome/src/components/TestResult/TrInfo/index.tsx]: The same logic is also used in `packages/web-awesome/src/components/TestResult/TrEnvironmentsView/index.tsx`. It could be extracted into a function that takes a `group` and returns the number of environments.

File: packages/web-awesome/src/components/TestResult/TrTabs/styles.scss [hunk 3]
```diff
@@ -37,9 +37,6 @@
     border-bottom: 2px solid transparent;
   }
 
-  &[disabled] {
```
Comment (delatrie) [inline packages/web-awesome/src/components/TestResult/TrTabs/styles.scss:40]: What were those disabled tabs you're removing? TBH, I don't remember having them previously... Is that a leftover that currently has no effect?

If not, if that's a removal of something that we used to have (not a leftover), let's mention it in the PR description.

**Review by delatrie — APPROVED** [review]
